name: sentinel
on:
  push:
  pull_request:
    branches:
      - master
jobs:
  sentinel-format:
    runs-on: ubuntu-latest
    container:
      image: hashicorp/sentinel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sentinel Format
        run: sentinel fmt -check=true $(find . -name "*.sentinel")
  sentinel-test:
    needs: sentinel-format
    runs-on: ubuntu-latest
    container:
      image: hashicorp/sentinel
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sentinel Test
        run: sentinel test $(find . -name "*.sentinel" ! -path "*/testdata/*")